#!/usr/bin/bash
# base (one shared script file) should be in "${KRUCIAI}/base", and it been
# been sourced in "src/${package_name}.sh" files
_OLD="$(pwd)"
export ARCHT="${ARCHT:-$(gcc -dumpmachine)}"
export ARCHM="${ARCHM:-$(uname -m)}"
export KRUCIAI="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${KRUCIAI}"
echo "--- ($(date)) $0 $@"
rm -rf AppDir
mkdir -p orig
mkdir -p envs

while [ -n "$1" ]
do case "$1" in
    --with-cha|--with-chawan)
    export USECHAWAN=YES
    shift;;

    -v|--version)
    echo -n "git "
    git rev-parse HEAD
    exit 0;;

    -h|--help)
    cat <<EOD
usage: $0 {OPTION}

OPTIONS:
--with-cha  enables chawan support
--help      display this page
--version   display version
EOD
    exit 0;;
esac
done

loop_break() {
    echo "$@"
    exit 8
}

pkgup() {
    local NAME="${1:-NONAME}"
    local HELPER="${KRUCIAI}/src/${NAME}.sh" # NAME=$1
    if [ ! -f "$HELPER" ] ; then exit 13 ; fi # FAIL: dependency is not found
    "${HELPER}" setup
    test -f "${KRUCIAI}/pool/${NAME}/ENV" && \
    source "${KRUCIAI}/pool/${NAME}/ENV" # file with environtment variables

    local SRC="${KRUCIAI}/pool/${NAME}/src"
    local DEST="${KRUCIAI}/pool/${NAME}/AppDir"
    local VER="${DEST}/etc/pkgup/installed/${NAME}"
    # also changes should be in "${DEST}/etc/pkgup/changes/${NAME}"
    local DEPS="$($HELPER deps)"
    echo "[pkgup] enter in: $1" #[${DEPS}]

    cd "${KRUCIAI}/pool/${NAME}"
    local UPD=0

    mkdir -p "${DEST}~"

    local DD
    for D in $DEPS
    do
        DD="${KRUCIAI}/pool/${D}/AppDir"

        # [ ! -f "${DEST}/etc/pkgup/installed/${NAME}" ] && \
        # ... means that you should provide order in dependencies,
        # from specific (that has ranged. of course) to ranged.
        pkgup "$D" && UPD=1

        echo "[pkgup] dependency of $1: $D"
        if [ -n "$DD" ]
        then cp -r "$DD/"* "${DEST}~"
        fi
    done

    if   [ ! -d "${SRC}" ]
    then # Package is new
        mkdir -p "$SRC"
        cd "$SRC"
        "${HELPER}" init
        UPD=1
    fi

    [ "$("${HELPER}" BREAK)" == "UPDATE" ] && loop_break "[pkgup] break: UPDATE"

    local VER_USED
    test -f "${VER}" && VER_USED="$(cat "${VER}")"
    cd "${SRC}"
    mkdir -p "${DEST}/etc/pkgup/changes"
    local VER_NEW="$("${HELPER}" update)"
    # So ${VER} is both marker that package localy installed and its version

    [ "$("${HELPER}" BREAK)" == "BUILD" ] && loop_break "[pkgup] break: BUILD"

    if   [ "$UPD" == 1 -o "$VER_USED" != "$VER_NEW" ]
    then # Updated or is new or is not $DEST
        rm -rf "${DEST}"
        mv "${DEST}~" "${DEST}"
        
        mkdir -p "${DEST}/etc/pkgup/installed"
        echo "${VER_NEW}" > "${VER}"

        "${HELPER}" build || ( rm "${VER}"; echo "`tput setaf 1`[pkgup] nobuild: ${HELPER}`tput sgr0`" )
        echo "[pkgup] updated: $1"

    else # Nothing happens with package(s)
        rm -rf "${DEST}~"
        
        mkdir -p "${DEST}/etc/pkgup/installed"
        echo "${VER_NEW}" > "${VER}"

        echo "[pkgup] stay: $1"
        return 25
    fi
    [ "$("${HELPER}" BREAK)" == "END" ] && loop_break "[pkgup] break: END"
}

pkgup dest

cd "${_OLD}"
unset KRUCIAI _OLD USECHAWAN ARCHT ARCHM
