#!/usr/bin/env bash

# AppImage Main-executable
export AIM="${AIM:-elinks}"
OWD="$(pwd)"
OLD_PATH="${PATH}"
OLD_MANPATH="${MANPATH}"

# Touch config
if [ ! -d "$HOME/.config/elinks" ]; then
    cp -r "${APPDIR}/etc/elinks" "$HOME/.config/elinks"
fi

# Setup env
cd "$APPDIR"
export PATH="${APPDIR}/usr/bin:${PATH}"
#export TEXTDOMAINDIR="${APPDIR}/usr/share/locale${TEXTDOMAINDIR:+:${TEXTDOMAINDIR}}"
#export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS:-${HOME}/.local/share:/usr/local/share:/usr/share}"
export MANPATH="${APPDIR}/usr/share/man${MANPATH:+:${MANPATH}}"
if [ -e ${APPDIR}/usr/bin/cha ]
then HAD_CHAWAN="true"
fi

if [ "$1" == "--save-cwd" ]
then
    cd "OWD"
    shift
fi

# Execute something
if [ "$1" -eq "--run" ] ; then
shift
case ${1:-$AIM} in
    help)
    echo "using: [ AIM=COMMAND ] $0 [ --save-cwd ] [ --run COMMAND ] [ ARGS ... ]

    commands:   description:
    sh, shell   runs shell in appimage root (\$APPDIR)
    qjs         runs quickjs' repl
    elinks      runs elinks${HAD_CHAWAN:+
    cha, chawan runs chawan}
    help        display this help page
    man         display \$AIM manpage

    if command is not found, then runs \$AIM
    "
    ;;

    sh|shell) shift
    ${SHELL:=bash} "$@"
    ;;

    qjs) shift
    qjs "$@"
    ;;

    elinks) shift
    elinks "$@"
    ;;

    cha|chawan) shift
    cha "$@"
    ;;

    man) shift
    man "${@:AIM}"
    ;;

    *) echo -e "command \"$@\" not recognized" ;;
esac
else
    "${AIM}" $@
fi

export PATH="${OLD_PATH}"
export MANPATH="${OLD_MANPATH}"
cd "${OWD}"

# Delete local variablle
unset AIM OWD OLD_PATH OLD_MANPATH
