#!/usr/bin/env bash

# AppImage Main-executable
export AIM="${AIM:-elinks}"
OWD="$(pwd)"
OLD_PATH="${PATH}"
OLD_MANPATH="${MANPATH}"

# Touch config
if [ ! -d "$HOME/.config/elinks" ]; then
	cp -r "${APPDIR}/etc/elinks" "$HOME/.config/elinks"
fi

# Setup env
cd "$APPDIR"
export PATH="${APPDIR}/usr/bin:${PATH}"
export TEXTDOMAINDIR="${APPDIR}"/usr/share/locale"${TEXTDOMAINDIR:+:${TEXTDOMAINDIR}}"
#export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS:-${HOME}/.local/share:/usr/local/share:/usr/share}"
export MANPATH="${APPDIR}/usr/share/man${MANPATH:+:${MANPATH}}"
if [ -e ${APPDIR}/etc/pkgup/installed/chawan ]
then HAD_CHAWAN="true"
fi

if [ "$1" == "--save-cwd" ]
then
	cd "OWD"
	shift
fi

# Execute something
if [ "$1" == "--run" ] ; then
shift
case ${1:-$AIM} in
	h|help)
	echo -e "using: [ AIM=COMMAND ] $0 [ --save-cwd ] [ --run COMMAND ] [ ARGS ... ]

commands:       description:

sh, shell       runs shell in appimage root (\$APPDIR)
man             display \$AIM manpage
help            display this help page
changes         list recent changes of programs
installed       list installed programs

qjs             runs quickjs' repl
elinks          runs elinks web-browser${HAD_CHAWAN:+
cha, chawan     runs chawan
mancha          runs chawan\'s wrapper for manpages}
";;

	sh|shell) shift
	${SHELL:=bash} "$@"
	;;

	qjs) shift
	qjs "$@"
	;;

	elinks) shift
	elinks "$@"
	;;

	cha|chawan) shift
	cha "$@"
	;;

	mancha) shift
	mancha "$@"
	;;

	man) shift
	man "${@:AIM}"
	;;

	c|changes) shift
	cd etc/pkgup/changes/
	for i in $(ls); do echo "--- ${i}"; cat "${i}"; done
	;;

	i|installed) shift
	cd etc/pkgup/installed/
	for i in $(ls); do echo "--- ${i}"; cat "${i}"; done
	;;

	*) echo -e "command \"$@\" not recognized" ;;
esac
else
	"${AIM}" $@
fi

export PATH="${OLD_PATH}"
export MANPATH="${OLD_MANPATH}"
cd "${OWD}"

# Delete local variablle
unset AIM OWD OLD_PATH OLD_MANPATH
